AppImagesSlider
vtex-apps/app-store-components pull request #4
Opened 2020-10-14 18:17 UTC by pedromtec

#### What does this PR do? \*
Create `AppImagesSlider` component. This component will display the app screenshots in the PDP.

```
"app-images-slider#screenshots": {
    "props": {
      "filterPattern": "screenshot",
      "sliderLayoutProps": {
        "itemsPerPage": {
          "desktop": 1,
          "tablet": 1,
          "phone": 1
        }
      },
      "blockClass": "screenshots"
    }
  }
```

#### How to test it? \*
[workspace](https://pricenew--extensions.myvtex.com/vtex-google-shopping/p)

2020-10-14 21:26 UTC, marlonguimaraes requested changes

2020-10-14 21:26 UTC, marlonguimaraes commented on react/components/AppImagesSlider.tsx
> +    : sortedImages.map((_, index) => sortedImages[numberOfImages - index - 1])
```suggestion
  const sortFunction = order === ASCENDING_ORDER ?
  (imageA, imageB) =>
    imageA[orderBy].localeCompare(imageB[orderBy]) : 
  (imageA, imageB) =>
    imageB[orderBy].localeCompare(imageA[orderBy])
  return images.sort(sortFunction)
```

2020-10-14 21:26 UTC, marlonguimaraes commented on react/components/AppImagesSlider.tsx
> +
```suggestion
const ASCENDING_ORDER = 'ASC'
const DESCENDING_ORDER = 'DESC'
const SORTING_ORDER = ASCENDING_ORDER | DESCENDING_ORDER
```

2020-10-14 21:26 UTC, marlonguimaraes commented on react/components/AppImagesSlider.tsx
> +  orderBy = 'imageId',
Use constant values when values are constants

```suggestion
  order = ASCENDING_ORDER,
   orderBy = IMAGE_ID_KEY
```

or something like that

2020-10-14 21:26 UTC, marlonguimaraes commented on react/components/AppImagesSlider.tsx
> +        ({ imageLabel }) => imageLabel.search(filterPattern) !== -1
```suggestion
        ({ imageLabel }) => imageLabel.test(filterPattern)
```

2020-10-14 22:34 UTC, pedromtec commented on react/components/AppImagesSlider.tsx
> +  orderBy = 'imageId',
Ok, but I think `IMAGE_ID_KEY` is not necessary because the orderBy type is `keyof Image`. 
`keyof Image` = `"cachedId" | "imageId" | "imageLabel" | "imageTag" | "imageText" | "imageUrl"` . `orderBy` can be any of these options and `typescript` helps with the check.

2020-10-14 22:37 UTC, pedromtec commented on react/components/AppImagesSlider.tsx
> +    : sortedImages.map((_, index) => sortedImages[numberOfImages - index - 1])
Nice, I will just use the name `compareFunction`.

2020-10-14 22:50 UTC, pedromtec commented on react/components/AppImagesSlider.tsx
> +
I don’t know why but typescript doesn’t allow to do something like:  `type SORTING_ORDER = ASCENDING_ORDER | DESCENDING_ORDER ` but I don't feel uncomfortable because `ASC` and `DESC` are very common alias in computer science. Databases uses it a lot: https://www.mysqltutorial.org/mysql-order-by/ .

2020-10-14 22:52 UTC, pedromtec commented on react/components/AppImagesSlider.tsx
> +        ({ imageLabel }) => imageLabel.search(filterPattern) !== -1
Nice

2020-10-14 22:54 UTC, pedromtec commented on react/components/AppImagesSlider.tsx
> +        ({ imageLabel }) => imageLabel.search(filterPattern) !== -1
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

2020-10-15 18:22 UTC, marlonguimaraes approved these changes

2020-10-20 19:37 UTC, juliarocha approved these changes
🚀

2020-10-20 19:39 UTC, lucis approved these changes
Nice!

I'd just check if the layout shifts, since the images are "heightless".

Refer: https://web.dev/cls/

2020-10-20 19:39 UTC, lucis commented on react/components/AppImagesSlider.tsx
> +          imageA[orderBy].localeCompare(imageB[orderBy])
I'd suggest some fail-proof here... 

If the user passes an invalid `orderBy`, it's possible that all of this breaks.

2020-10-20 20:32 UTC, pedromtec commented on react/components/AppImagesSlider.tsx
> +          imageA[orderBy].localeCompare(imageB[orderBy])
@lucis, I think I can add a try catch like this: 
```
try {
    return images.sort(compareFunction)
  } catch (e) {
    console.error(`${orderBy} is not a key of Image`)
    return images
  }
```

2020-10-22 16:47 UTC, merged