Feature/login logout
vtex-apps/app-store-components pull request #5
Opened 2020-10-19 20:21 UTC by marlonguimaraes

#### What does this PR do? \*

Provide a component for App Store login

#### How to test it? \*

1)  Access https://marlon--extensions.myvtex.com/
2) Click on "Login"

2020-10-26 20:55 UTC, arturpimentel requested changes

2020-10-26 20:55 UTC, arturpimentel commented on react/components/LoginLogout.tsx
> +import { useCssHandles } from 'vtex.css-handles'
Nitpick: put React imports on top. It just looks a little bit cleaner

```suggestion
import React, { Fragment, useEffect, useState } from 'react'

import { LoginAccountDialog } from 'extensions.account-dialog'
import { useCssHandles } from 'vtex.css-handles'
```

2020-10-26 20:55 UTC, arturpimentel commented on react/components/LoginLogout.tsx
> +  const [startedLogin, setStartedLogin] = useState<boolean>(false)
Can we merge these statuses into one? It could be easier to scale
```suggestion
  const [loginStatus, setLoginStatus] = useState<'unknown' | 'authenticating' | 'authenticated' | 'unauthenticated'>('unknown')
```

2020-10-26 20:55 UTC, arturpimentel commented on react/utils.ts
> +}
You can also use [react-cookie](https://www.npmjs.com/package/react-cookie) for a cleaner approach

2020-10-26 20:55 UTC, arturpimentel commented on react/components/LoginLogout.tsx
> +  const onClick = (_: React.MouseEvent) => {
```suggestion
  const handleClick = (_: React.MouseEvent) => {
```

2020-10-26 20:55 UTC, arturpimentel commented on react/components/LoginLogout.tsx
> +        {loginButtonText}
Should we render a spinner instead of nothing when evaluating the login status?

2020-11-03 18:18 UTC, marlonguimaraes commented on react/components/LoginLogout.tsx
> +import { useCssHandles } from 'vtex.css-handles'
Our lints are configured to order imports in alphabetical order and no line between them: 
![image](https://user-images.githubusercontent.com/12221113/98024943-cf72f300-1de7-11eb-8e67-a9b1f1144e5d.png)

Should we change this configuration?

2020-11-03 21:52 UTC, marlonguimaraes commented on react/utils.ts
> +}
Nice!

2020-11-03 21:52 UTC, marlonguimaraes commented on react/components/LoginLogout.tsx
> +  const [startedLogin, setStartedLogin] = useState<boolean>(false)
Sounds better, thanks!

2020-11-04 17:03 UTC, arturpimentel approved these changes

2020-11-04 17:04 UTC, arturpimentel commented on react/components/LoginLogout.tsx
> +import { useCssHandles } from 'vtex.css-handles'
Hmmmm I see. Keep the way it is, then

2020-11-06 14:22 UTC, pedromtec requested changes

2020-11-06 14:22 UTC, pedromtec commented on react/components/LoginLogout.tsx
> +declare global {
Where are you using it ?

2020-11-06 14:45 UTC, marlonguimaraes commented on react/components/LoginLogout.tsx
> +declare global {
Good eyes! Nothing really, that was probably something I thought I needed in the beggening but forgot to remove. Removed in 9861ac83db6ad9ef5032e74e75854cf67997bb05, thanks!

2020-11-06 14:54 UTC, pedromtec commented on react/components/LoginLogout.tsx
> +
```suggestion
const useAppStoreAuth = () => {
  const [cookies, , removeCookie] = useCookies([COOKIE_LOGIN_EXP])

  const isAuthenticated = () => {
    const exp = cookies[COOKIE_LOGIN_EXP]
    return !!exp && parseInt(exp, 10) > Date.now()
  }

  const deleteCookie = () => removeCookie(COOKIE_LOGIN_EXP, {
    path: '/',
  })

  return [isAuthenticated, deleteCookie]
}

```

2020-11-06 15:09 UTC, marlonguimaraes commented on react/components/LoginLogout.tsx
> +
I think I prefer to keep them splitted, they may be used independently and code looks simpler to understand

2020-11-06 16:17 UTC, pedromtec approved these changes

2020-12-02 18:16 UTC, merged