Feat/app store conditional component
vtex-apps/app-store-components pull request #6
Opened 2020-11-06 17:59 UTC by pedromtec

#### What does this PR do? \*

Create a component to block pages in specific scenarios. 

#### How to test it? \*
[workspace](https://pedrocheckout--extensions.myvtex.com/)

Try to access: `/cart` and `/checkout`

2020-11-06 18:58 UTC, arturpimentel approved these changes

2020-11-09 16:19 UTC, marlonguimaraes requested changes

2020-11-09 16:19 UTC, marlonguimaraes commented on react/components/AppStoreCondition.tsx
> +const AppStoreCondition: React.FC<Props> = ({
Acho que não dá pra deduzir o que esse componente faz só lendo o nome. Eu colocaria algum nome que tem `login` no meio:

```suggestion
const RedirectIfNotLoggedIn: React.FC<Props> = ({
```

ou 

```suggestion
const WithUserLoggedIn: React.FC<Props> = ({
```

(Lembrar de atualizar os nomes dos arquivos se renomear)

2020-11-18 20:43 UTC, pedromtec commented on react/components/AppStoreCondition.tsx
> +const AppStoreCondition: React.FC<Props> = ({
Mas o problema é que esse bloco n bloqueia apenas usuários logados. Ele pode bloquear qualquer usuário.

2020-11-18 20:44 UTC, pedromtec commented on react/components/AppStoreCondition.tsx
> +const AppStoreCondition: React.FC<Props> = ({
Tipo, /cart

2020-11-18 20:50 UTC, marlonguimaraes commented on react/components/AppStoreCondition.tsx
> +const AppStoreCondition: React.FC<Props> = ({
Meu ponto é que o nome AppStoreCondition é genérico, não dá pra entender o que esse componente faz lendo o nome

2020-11-18 20:59 UTC, marlonguimaraes approved these changes
Ainda acho o nome `AppStoreCondition` muito genérico, colocaria algo mais especifíco do comportamento do componente, tirando isso LGTM

2020-12-03 13:55 UTC, merged